branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: mysite
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
