branch-defaults:
  master:
    environment: mysite-dev
    group_suffix: null
environment-defaults:
  mysite-dev:
    branch: null
    repository: null
global:
  application_name: mysite
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
